//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE.SDKtoAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICE.SDKtoAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2~BaseLoanAmount~True~decimal~False~Trans Details Total Loan Amt (w/ MIP/FF)~False~~DECIMAL_2
        ///3~RequestedInterestRatePercent~False~decimal~False~Trans Details Interest Rate~False~~DECIMAL_2
        ///4~LoanAmortizationTermMonths~False~int~False~Trans Details Term (Mos)~False~~INTEGER
        ///5~PrincipalAndInterestMonthlyPaymentAmount~False~decimal~False~Trans Details Mo Pymt (P&amp;I)~True~~DECIMAL_2
        ///6~Fees[FeeType=UserDefinedFee_817].SellerPaidAmount~False~decimal~False~Fees Line 817 Seller~False~~DECIMAL_2
        ///8~RegulationZ.P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryFieldsV1 {
            get {
                return ResourceManager.GetString("DictionaryFieldsV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2~BaseLoanAmount~True~decimal~True~Trans Details Total Loan Amt (w/ MIP/FF)~False~~DECIMAL_2
        ///3~RequestedInterestRatePercent~False~decimal~True~Trans Details Interest Rate~False~~DECIMAL_3
        ///4~LoanAmortizationTermMonths~False~int~True~Trans Details Term (Mos)~False~~INTEGER
        ///5~PrincipalAndInterestMonthlyPaymentAmount~False~decimal~True~Trans Details Mo Pymt (P&amp;I)~False~~DECIMAL_2
        ///6~Fees[FeeType=UserDefinedFee_817].SellerPaidAmount~False~decimal~True~Fees Line 817 Seller~False~~DECIMAL_2
        ///8~RegulationZ.PmiIn [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DictionaryFieldsV3 {
            get {
                return ResourceManager.GetString("DictionaryFieldsV3", resourceCulture);
            }
        }
    }
}
